name: adm_server
description: A Dart Mock Server is an experimental mock server with full Http Message response control.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  http: ^0.13.5
  intl: ^0.18.0
  logging: ^1.1.0
  path: ^1.8.3
  shelf: ^1.4.0
  yaml: ^3.1.1

dev_dependencies:
  lints: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.16.0
