setup:
	chmod +x adms-v0.0.1-alpha-linux-amd64.exe
	chmod +x pipe-example.py

start:
	./adms-v0.0.1-alpha-linux-amd64.exe

test-data:
	curl localhost:7777/data-example

test-pipe:
	curl localhost:7777/pipe-example