# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference

version: 2.1

jobs:
    unit-test-job:
        machine:
            image: ubuntu-2204:2022.10.2

        steps:
            # setup dart
            - run:
                  name: 'Get Dart'
                  command: 'wget https://storage.googleapis.com/dart-archive/channels/stable/release/latest/linux_packages/dart_2.18.6-1_amd64.deb -O ~/dart.deb'

            - run:
                  name: 'Install Dart'
                  command: 'sudo dpkg --force-confold -i ~/dart.deb'

            - checkout

            - run:
                  name: 'Dart Dependencies'
                  command: 'dart pub get'

            # run test
            - run:
                  name: 'Dart Test (full)'
                  command: 'dart test'

            # generate coverage
            - run:
                  name: 'Get CodeCov'
                  command: 'curl -Os https://uploader.codecov.io/v0.1.0_4653/linux/codecov && chmod +x codecov'
            - run:
                  name: 'Test with coverage'
                  command: 'dart run coverage:test_with_coverage'

            - run:
                  name: 'Format coverage'
                  command: 'dart run coverage:format_coverage -i coverage/coverage.json'

            - run:
                  name: 'Upload coverage to CodeCov'
                  command: ./codecov -t ba3ac644-3887-4b26-8733-1c9df8db6fa9

workflows:
    test-workflow:
        jobs:
            - unit-test-job
